app = "telegram-proxy-free"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  WORKERS = "1"

[http_service]
  internal_port = 443
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  internal_port = 443
  protocol = "tcp"

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"

[[services]]
  internal_port = 8888
  protocol = "tcp"

  [[services.ports]]
    port = 8888

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 